ENVIRONMENT = "LOCAL"
HOST_URL = "https://www.scribd.com/doc/" # Document hosting
SCRIBD_API_KEY = "Change this" # If using Scribd for document hosting
SCRIBD_API_SECRET = "Change this" # If using Scribd for document hosting
DEFAULT_OWNER_EMAIL = "Change this"
DEFAULT_OWNER_REASON = "Change this"
MAIL_USERNAME = "Change this"
MAIL_PASSWORD = "Change this"
DEFAULT_MAIL_SENDER = "Change this"
SECRET_KEY = "Change this"
SQLALCHEMY_DATABASE_URI = "postgresql://localhost/your_database_name"
ADMIN_PASSWORD = 'Change this'