"""Adding password to user

Revision ID: 10428b97f3d3
Revises: 52e0f17be3d7
Create Date: 2013-05-31 14:26:33.058126

"""

# revision identifiers, used by Alembic.
revision = '10428b97f3d3'
down_revision = '52e0f17be3d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
