"""Adding access field to record

Revision ID: 106df64301aa
Revises: 10428b97f3d3
Create Date: 2013-06-07 02:04:50.891890

"""

# revision identifiers, used by Alembic.
revision = '106df64301aa'
down_revision = '10428b97f3d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('access', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'access')
    ### end Alembic commands ###
