"""Add active flag to User table

Revision ID: 134e5fea7601
Revises: None
Create Date: 2014-07-09 16:55:35.820805

"""

# revision identifiers, used by Alembic.
revision = '134e5fea7601'
down_revision = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), server_default='False'))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    ### end Alembic commands ###

