"""Added viz table

Revision ID: 182a18c7d812
Revises: eb59e2ec22a
Create Date: 2013-10-10 17:47:52.007837

"""

# revision identifiers, used by Alembic.
revision = '182a18c7d812'
down_revision = 'eb59e2ec22a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'visualization',
    	sa.Column('id', sa.Integer(), nullable = False),
    	sa.Column('content', sa.String(), nullable = False),
    	sa.Column('date_created', sa.DateTime(), nullable = False),
    	sa.Column('date_updated', sa.DateTime(), nullable = True),
    	sa.Column('type_viz', sa.String(), nullable = False),
    	sa.PrimaryKeyConstraint('id')
    	)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'visualization')
    ### end Alembic commands ###