"""adding phone number to request

Revision ID: 19deb18bd31e
Revises: None
Create Date: 2013-05-30 14:05:20.726220

"""

# revision identifiers, used by Alembic.
revision = '19deb18bd31e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    ### end Alembic commands ###
