"""Added contact_for and backup_for fields to User

Revision ID: 1b149799fff2
Revises: None
Create Date: 2013-10-08 13:57:22.377472

"""

# revision identifiers, used by Alembic.
revision = '1b149799fff2'
down_revision = '3c1a22430b4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_for', sa.String(), nullable=True))
    op.add_column('user', sa.Column('backup_for', sa.String(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact_for')
    op.drop_column('user', 'backup_for')
    ### end Alembic commands ###
