"""Adding download url field to Record

Revision ID: 1ec8077855b1
Revises: 568154e02d86
Create Date: 2013-07-09 22:59:15.909734

"""

# revision identifiers, used by Alembic.
revision = '1ec8077855b1'
down_revision = '568154e02d86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('download_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'download_url')
    ### end Alembic commands ###
