"""removing phone from request

Revision ID: 239cbd50172b
Revises: 38f1c3cdeae4
Create Date: 2013-05-30 15:07:59.455644

"""

# revision identifiers, used by Alembic.
revision = '239cbd50172b'
down_revision = '38f1c3cdeae4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', u'phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'phone', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
