"""Added is_point_person column to Owner

Revision ID: 2734ab9c8c88
Revises: bac545ba944
Create Date: 2014-03-14 21:12:46.312089

"""

# revision identifiers, used by Alembic.
revision = '2734ab9c8c88'
down_revision = 'bac545ba944'
# down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('is_point_person', sa.Boolean(), server_default='False'))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'is_point_person')
    ### end Alembic commands ###


