"""Removing owner_id and adding user_id to record

Revision ID: 2942fd1357e3
Revises: 106df64301aa
Create Date: 2013-06-07 02:21:19.175308

"""

# revision identifiers, used by Alembic.
revision = '2942fd1357e3'
down_revision = '106df64301aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('record', u'owner_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column(u'owner_id', sa.INTEGER(), nullable=True))
    op.drop_column('record', 'user_id')
    ### end Alembic commands ###
