"""Added should_notify column to Subscriber

Revision ID: 30d3af507801
Revises: 182a18c7d812
Create Date: 2013-10-30 21:37:43.600038

"""

# revision identifiers, used by Alembic.
revision = '30d3af507801'
down_revision = '182a18c7d812'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('should_notify', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'should_notify')
    ### end Alembic commands ###