"""Add due date
Revision ID: 383c463bc850
Revises: 26cee7734778
Create Date: 2014-04-17 21:57:37.492270

"""

# revision identifiers, used by Alembic.
revision = '383c463bc850'
down_revision = '26cee7734778'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('due_date', sa.DateTime()))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'due_date')
    ### end Alembic commands ###


