"""adding phone to request

Revision ID: 38f1c3cdeae4
Revises: 19deb18bd31e
Create Date: 2013-05-30 15:06:40.019162

"""

# revision identifiers, used by Alembic.
revision = '38f1c3cdeae4'
down_revision = '19deb18bd31e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
