"""adding phone number to request

Revision ID: 390851866176
Revises: 239cbd50172b
Create Date: 2013-05-30 15:15:25.467338

"""

# revision identifiers, used by Alembic.
revision = '390851866176'
down_revision = '239cbd50172b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    ### end Alembic commands ###
