"""Changed request text type from string to text

Revision ID: 454d11306d95
Revises: 2942fd1357e3
Create Date: 2013-06-24 23:13:12.471996

"""

# revision identifiers, used by Alembic.
revision = '454d11306d95'
down_revision = '2942fd1357e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
