"""Add offline columns to Request

Revision ID: 49b52a2b959f
Revises: 2734ab9c8c88
Create Date: 2014-03-22 15:43:57.021825

"""

# revision identifiers, used by Alembic.
revision = '49b52a2b959f'
down_revision = '2734ab9c8c88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('date_received', sa.DateTime()))
    op.add_column('request', sa.Column('offline_submission_type', sa.String()))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'date_received')
    op.drop_column('request', 'offline_submission_type')
    ### end Alembic commands ###


