"""Removing creator from subscriber

Revision ID: 52e0f17be3d7
Revises: None
Create Date: 2013-05-30 16:09:15.687066

"""

# revision identifiers, used by Alembic.
revision = '52e0f17be3d7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
