"""Added extended flag to Request

Revision ID: 568154e02d86
Revises: 454d11306d95
Create Date: 2013-07-08 12:32:00.177624

"""

# revision identifiers, used by Alembic.
revision = '568154e02d86'
down_revision = '454d11306d95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('extended', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'extended')
    ### end Alembic commands ###
