"""Adding department table

Revision ID: 2c77635aac0c
Revises: 5563ca9e7626
Create Date: 2014-03-13 02:57:58.263517

"""

# revision identifiers, used by Alembic.
revision = '8ce10875836'
down_revision = '5563ca9e7626'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    ### end Alembic commands ###
