"""Add department ID to Request

Revision ID: bac545ba944
Revises: 55c0f777cb74
Create Date: 2014-03-13 23:57:39.455646

"""

# revision identifiers, used by Alembic.
revision = 'bac545ba944'
down_revision = '55c0f777cb74'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('department_id', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'department_id')
    ### end Alembic commands ###