"""Add department field to Request table

Revision ID: eb59e2ec22a
Revises: 1b149799fff2
Create Date: 2013-10-08 14:48:25.187224

"""

# revision identifiers, used by Alembic.
revision = 'eb59e2ec22a'
down_revision = '1b149799fff2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('department', sa.String(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'department')
    ### end Alembic commands ###
