= DB Helpers
Description of the functions in the `db_helpers.py` file.
:toc:
:source-highlighter: pygments

link:index.html[back to index page]


== get_obj
This searches the database for an object via its class/type (defined in the
`models.py` file) and ID and returns the object:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_obj'] }}

== get_objs
This searches the database for all objects of a certain class/type (defined in
the "models.py" file) and returns a queryset.

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_objs'] }}</p>

== get_request_by_owner
Retrieves a request associated with a particular owner:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_request_by_owner'] }}

== get_owners_by_user_id
A user can be associated with multiple owners. Gets owner by their user ID:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_owners_by_user_id'] }}

== get_requests_by_filters
Retrieves requests based on filters provided:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_requests_by_filters'] }}

== put_obj
Adds a particular object to the database:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['put_obj'] }}

== update_obj
Obtain the object its ID and type, if the object is not provided, and updates
the specified attribute for that object. If the command is successful, returns
the word 'true.':

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['update_obj'] }}
 
== get_attribute
Gets an object by its ID and type to return the specified attribute for that
object, if the object is not provided:

{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['get_attribute'] }}

== create_QA
Creates a question object and return its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_QA'] }}

== create_request
Creates an object for a request and returns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_request'] }}

== create_subscriber
 Creates an object for the subscriber and returns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_subscriber'] }}

== create_note
 Creates an object for a note and returns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_note'] }}

== create_record
 Creates an object for an uploaded record and returns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_record'] }}

== create_answer
Creates an object for the public's response to a particular question and returns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_answer'] }}

== create_or_return_user
Creates an object for a user and retruns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_or_return_user'] }}

== create_user
Creates an object for a user and retruns its ID.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['create_user'] }}

== update_user
Update a city employee's phone number, department, and password.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['update_user'] }}

== update_user
This important for multi-departmental requests. It adds a city employee to a request as a "helper," but does not change the point of contact for a request.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['update_user'] }}

== change_request_status
This changes the status of a particular request. City employees see three different statuses: open, overdue, and closed. The only statuses members of the public see are open and closed. 
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['change_request_status'] }}

== find_request
Allows users to search through requests by entering a word or phrase.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['find_request'] }}

== find_owner
Allows users to search through requests by owner, or city employee who is responsible for fulfilling a particular request.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['find_owner'] }}

== add_staff_participant
Creates an owner for the request if it doesn't exist. The owner ID is returned as True if a new one is created, and false if it already exists.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['add_staff_participant'] }}

== authenticate_login
City employees are required to enter a username and password to upload records and send messages to requesters. The username is currently a city employee's official email address.
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['authenticate_login'] }}

== set_random_password
If users forget their password, a new random password is assigned to them so they are able to log into the system. This funcationality is limited to existing users. Currently users of the system are limited to offical city of Oakland employees. 
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['set_random_password'] }}

== set_password
Allows city employees to change their passwords:
{{ d['/public_records_portal/db_helpers.py|idio|asciisyn']['set_password'] }}

