= Departments
Description of the functions in the `departments.py` file. Generally contains the code related to a municipality's departments or agencies.
:toc:
:source-highlighter: pygments

link:index.html[back to index page]

== create_doctypes
Creates a file called "doctypes.json" from "departments.json." We use "doctypes.json" to map document types to the department which can fulfill it in the typeahead feature on the new request page.
{{ d['/public_records_portal/departments.py|idio|asciisyn']['create_doctypes'] }}

== create_list_depts
Creates an array of of the departments.
{{ d['/public_records_portal/departments.py|idio|asciisyn']['create_list_depts'] }}

== get_dept_backup
Retrieves the backup Public Records Request (PRR) liaison for a particular department. This person is responsible for fulfilling a public records request when a PRR liaison is not available.
{{ d['/public_records_portal/departments.py|idio|asciisyn']['get_dept_backup'] }}

== get_dept
Given a user object (defined in the 'models.py' file), this checks to see if the user's email is in the "departments.json" file. If the user is not in the 'departments.json' file
{{ d['/public_records_portal/departments.py|idio|asciisyn']['get_dept'] }}

== populate_users_with_departments
This associates city employee with a particular department.
{{ d['/public_records_portal/departments.py|idio|asciisyn']['populate_users_with_departments'] }}
 