== How a Responder Uses RecordTrac

A responder is typically an employee of a governmental agency. 

=== Re-Route Request
A city employee can send the request to another individual in the official city directory if their department is unable to fulfill it. The city employee will be alerted via email and will become the new point of contact for this request.

=== Add a Helper
Sometimes more than one person is needed to fulfill a request or it involves multiple departments. Click on 'Helpers' to notify additional city employees of this request.

=== Ask a Question
A city employee can ask questions about this particular records request. The requester will be notified via email of this question. The question will be posted online for everyone to view.

=== Upload a Record
Documents stored on a computer can be uploaded. The requester will be notified via email every time a record is uploaded. The documents will be posted online for everyone to view.

Records are displayed online via Scribd. Supported file types are the following:
'txt', 'pdf', 'doc', 'ps', 'rtf', 'epub', 'key', 'odt', 'odp', 'ods', 'odg', 'odf', 'sxw', 'sxc', 'sxi', 'sxd', 'ppt', 'pps', 'xls', 'zip', 'docx', 'pptx', 'ppsx', 'xlsx', 'tif', 'tiff'

=== Add An Offline Record
Some records cannot be uploaded to the website and requesters will have to be told when and where to pick up copies of it. The requester will be notified via email about this message. This message will be posted online for everyone to view.

=== Add a Link to Another Website

A city employee can respond to a request by providing a link to where the document or information is stored online. The requester will be notified via email about this link. This web address will be posted online for everyone to view.

=== Add a Note
Updates can be provided to the requester through the "Add a Note" feature. The requester will be notified via email. The message will be posted online for everyone to view.

=== Request an Extension
Notify a requester if additional time is needed to fulfill their public records request. Select from one of the four legal reasons to extend a request and edit the message. The due date of the request changes, giving the city employee 14 additional calendar days to respond to the request. The message is posted online and the requester is notified via email. _An extension can only be requested once._

=== Closing a Request
To close out a request, city employees can edit a message already provided to them. An email is then sent to the requester notifying them the request is closed. The status of the request will also change. 

=== Re-Open a Request
Allows you to re-open a request after it is closed. This makes it possible for you to send more messages and upload additional records.

== What is Unique to the City View

There are two views in RecordTrac: the city employee view and the public view. Any time there is a web page only a city employee who is logged should see there is 'city' in the URL. Ex: http://records.oaklandnet.com/city/request/952.    

City employees are the only users able to upload records, extend a request, close a request, and correspond with the requester through RecordTrac. 

Only city employees can view:
* A requester's name
* A requester's phone number
* A particular request's due date. This information is hidden from the public.
* Whether a request is overdue or due soon. Members of the public are only able to tell whether a request is open or closed.

== Tutorial

RecordTrac's tutorial shows government employees how to successfully manage a public records request with RecordTrac. The tutorial was created to quickly on-board new employees who are responsible for fulfilling public records requests. Only government employees who are logged into RecordTrac are able to view the tutorial. 

You can view the tutorial by going to http://records.oaklandnet.com/tutorial[records.oaklandnet.com/tutorial].  