= Models
Description of the tables in the database, as defined in `models.py`.
:toc:
:source-highlighter: pygments

link:index.html[back to index page]

== User
User is a table in the public records database.
{{ d['/public_records_portal/models.py|idio|asciisyn']['User'] }}

== Request
This is the actual public records request submitted by a member of the public. The table collects:

* Date the request was submitted 
* Has the due date been extended?
* List of question and answer units for a particular request
* When the status of a request is updated
* The actual request text
* The list of 'subscribers' following a request text. 'Subscribers' are members of the public who didn't initially submit the request, but is interested in the results.
* All city staff members who ever were assigned to a request 
* The Owner ID for the city staff who is listed as the point of contact for a request and is responsible for fulfilling the request. 
* The list of records associated with a particular request.
* The list of notes associated with a particular request.
* The status of the request
* The creator of the request. City staff sometimes enter messages in the system on the requesters behalf. 
 
{{ d['/public_records_portal/models.py|idio|asciisyn']['Request'] }}

== QA
Creates a table of information on the Question and Answer block for a particular request: 
 {{ d['/public_records_portal/models.py|idio|asciisyn']['QA'] }}   

== Owner
Creates a table of information about the city employee assigned to a particular request. This is the 'owner' of the request or the 'point of contact.' City staff may or may not upload records.
{{ d['/public_records_portal/models.py|idio|asciisyn']['Owner'] }}  

== Subscriber
Creates a table of information about an individual subscribed to the request. The subscriber may have not been the one to create the request. It could be someone simply interested in the outcome of particular request. The subscriber could potentially be a city employee.
{{ d['/public_records_portal/models.py|idio|asciisyn']['Subscriber'] }}

== Record
Information about records are stored in a table. Records can be uploaded documents, links to another website, or instructions on how a requester can view or pick up copies of a document. The following information is collected in this table:

* Date created
* The user who uploaded the record. Now only city staff members are allowed to upload records.
* The document ID. Currently using Scribd API to upload documents. In the future, the city's content management system may be used.
* The request the record is associated with.
* A short description of the record.
* The original name of the file being uploaded.
* Where the records exists online
* Where the record can be downloaded online
* Instructions on where to access offline documents.

{{ d['/public_records_portal/models.py|idio|asciisyn']['Record'] }}

== Note
Creates a table of information on the notes posted by city staff and members of the public. 
{{ d['/public_records_portal/models.py|idio|asciisyn']['Note'] }}
