= Notifications
Description of the functions in the `notifications.py` file. Sends out email notifications for the web application.
:toc:
:source-highlighter: pygments

link:index.html[back to index page]

== generate_prr_emails
The code below generates the emails for the public records request application. City staff receive notifications every time a request is submitted for them to fulfill, when a request is due in two days, when a request is overdue, and when a member of the public responds to one of their questions. Requesters get emails once their request is submitted, if a city employee has a question about their request, when a message or document is uploaded, and when the request is closed.
{{ d['/public_records_portal/notifications.py|idio|asciisyn']['generate_prr_emails'] }} 

Some key details about the emails are listed below: 

* Each request is assigned a unique ID. The unique ID is displayed in the subject line to allow the recipient of the emails to determine which request is associated with that particular notification
* The unsubscribe link is not included in city employee emails. This is to prevent them from accidentally unsubscribing from the email notifications.
* Four types of people can receive email notifications: the original requester; the 'subscriber' or interested member of the public who wants to know when a particular records request is fulfilled; the staff owner (also known as a 'point of contact') or staff member responsible for fulfilling the records request; and the staff participants (also known as a 'helper') or the city employees who help the owner fulfill a request.

== send_prr_email
Sends emails to city employees or city staff members after they are generated.
{{ d['/public_records_portal/notifications.py|idio|asciisyn']['send_prr_email'] }} 

== send_email
Sendgrid wrapper to send email
{{ d['/public_records_portal/notifications.py|idio|asciisyn']['send_email'] }}

== due_date
Calculates the due date. The California Public Records Act gives city employees ten days to respond to a request. The request is due ten calendar days after it is submitted. When a request is extended, a city employee only gets 14 additional days to respond.
{{ d['/public_records_portal/notifications.py|idio|asciisyn']['due_date'] }}

== is_due_soon
An email is sent to the staff owner and participants two days before a request is due. This calculates the date that email is sent out:
{ d['/public_records_portal/notifications.py|idio|asciisyn']['is_due_soon'] }}

== is_overdue
An email is sent to the staff owner and participants when a request is due. This calculates the date that email is sent out:
{ d['/public_records_portal/notifications.py|idio|asciisyn']['is_overdue'] }}

== get_email_info
This pulls information about email notifications from the 'Emails.json' file. The .json file contains each email notification's subject lines and who should receive the email.
{ d['/public_records_portal/notifications.py|idio|asciisyn']['get_email_info'] }}

== notify_due
Before email notifications are sent, the system must first check to see if the request is open or closed. Notifications are only sent about open requests. Then the request is checked to determine if it is either due in two days or if it's past due. Currently there is not way to pass the generic email template outside of the application context. For now, hardcoding the body. 
{ d['/public_records_portal/notifications.py|idio|asciisyn']['notify_due'] }}

== should_notify
Some city employees may not want to be sent email notifications. If they shouldn't receive emails, add the email addresses to the 'do_not_email.json' file. This line of code prevents the people in that file from being sent emails:
{ d['/public_records_portal/notifications.py|idio|asciisyn']['should_notify'] }}

== format_date
{ d['/public_records_portal/notifications.py|idio|asciisyn']['format_date'] }}
