= PRR
Description of the functions in the `prr.py` file.
:toc:
:source-highlighter: pygments

link:index.html[back to index page]

== make_request

Members of the public can submit a message to city employees requesting a public record. At a minimum, they are required to enter a message. Currently, we require an email address because the large amount of spam being received.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['make_request'] }} 

== answer_a_question
A requester can respond to a question asked by a city employee.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['answer_a_question'] }}

== add_subscriber
If an individual is interested in the outcome of a particular request, they can subscribe to a request and receive email updates every time a response is added to the particular request or it is closed.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['add_subscriber'] }}

== assign_owner
A city employee can send the request to another individual in the official city directory if their department is unable to fulfill it. The city employee will be alerted via email and will become the new point of contact for this request.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['assign_owner'] }} 

== ask_a_question
A city employee can ask questions about this particular records request. The requester will be notified via email of this question. The question will be posted online for everyone to view.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['ask_a_question'] }}

== upload_record
Documents stored on a computer can be uploaded. The requester will be notified via email every time a record is uploaded. The documents will be posted online for everyone to view.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['upload_record'] }}

== add_offline_recoord
Some records cannot be uploaded to the website and requesters will have to be told when and where to pick up copies of it. The requester will be notified via email about this message. This message will be posted online for everyone to view.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['add_offline_record'] }}

== add_link
A city employee can respond to a request by providing a link to where the document or information is stored online. The requester will be notified via email about this link. This web address will be posted online for everyone to view.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['add_link'] }}

== add_note
Updates can be provided to the requester through the "Add a Note" feature. The requester will be notified via email. The message will be posted online for everyone to view.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['add_note'] }}

== request_extension
Notify a requester if additional time is needed to fulfill their public records request. Select from one of the four legal reasons to extend a request and edit the message. The due date of the request changes, giving the city employee 14 additional calendar days to respond to the request. The message is posted online and the requester is notified via email.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['request_extension'] }}
  
== close_request
To close out a request, city employees can edit a message already provided to them. An email is then sent to the requester notifying them the request is closed. The status of the request will also change.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['close_request'] }}

== open_request

Allows you to open or re-open a request after it is closed. This makes it possible for you to send more messages and upload additional records.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['open_request'] }}

== get_request_data_chronologically
This command displays all of the information in the request block in chronological order. This mainly includes all of the questions asked by city employees and responses from members of the public. 
{{ d['/public_records_portal/prr.py|idio|asciisyn']['get_request_data_chronologically'] }}
  
== get_responses_chronologically
This command displays all city employee responses in chronological order. This mainly includes any uploaded messages and documents. 
{{ d['/public_records_portal/prr.py|idio|asciisyn']['get_responses_chronologically'] }}

== is_request_open
Retrieves the status of the request to determine whether or not it's open.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['is_request_open'] }}

== set_directory_fields
This displays the contact information for city employees. This data is pulled for the "directory.json" file.
{{ d['/public_records_portal/prr.py|idio|asciisyn']['set_directory_fields'] }} 