== How a Requester Uses RecordTrac

=== Make a Request
Members of the public can submit a message to city employees requesting a public record. At a minimum, they are required to enter a message. 

* There is no limit to the amount of text they can put in the request field.
* If a requester types in birth, death, marriage, or divorce in the request field, they are prompted to go to the county's website. The county maintains records for birth, deaths, marriages, and divorces. 
* Requester are able to enter the department they want the request sent to or the type of document they need. 
* The department or document type field is used to select which person initially receives the request. 
* If a department is not selected, it the request is automatically routed to the Open Government Coordinator in the City Attorney's office. 
* All contact information is optional, although we strongly encourage the requester to provide an email address. The California Public Records Acts

=== Answer a Question
A requester can respond to a question asked by a city employee. 

=== Add a Note
The requester can add a note if they need to provide additional information to the municipality about their public records request. This feature was added to encourage all communication to occur within RecordTrac. 

=== Subscribe to a Request
If an individual is interested in the outcome of a particular request, they can subscribe to a request. They will receive email updates every time a response is added to the particular request or it is closed.